[package]
name = "aoc2020"
version = "0.1.0"
authors = ["HaNaK0 <saturn-v@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vector2d = "2.2.0"